# Basic Configuration
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Lerian Studio Blog'

# Theme Configuration
theme = 'compose'

# Content Configuration
summaryLength = 30
defaultContentLanguage = 'en'
enableEmoji = true
enableGitInfo = true
# URL Configuration
canonifyURLs = true

# Pagination
[pagination]
  pagerSize = 10

# Compose Theme Parameters
[params]
  # Meta
  author = "Lerian Studio"
  description = "Thoughts, ideas, and projects from Lerian Studio"
  
  # Logo and favicon
  [params.logo]
    lightMode = "/favicon.png"
    darkMode = "/favicon.png"
  favicon = "/favicon.png"
  
  # Theme customization
  themeColor = "#000000"
  accentColor = "#ffff00"
  showSocialLinks = true
  showToc = true
  showDate = true
  showReadTime = true
  showAuthor = true
  showLikes = false
  
  # Search
  enableSearch = true
  searchProvider = "fuse"
  
  # Code highlighting
  enableHighlight = true
  highlightStyle = "monokai"
  
  # Social media links
  [params.social]
    github = "https://github.com/lerianstudio"
    twitter = "https://twitter.com/lerianstudio"
    linkedin = "https://linkedin.com/in/lerianstudio"
    
  # Custom footer
  [params.footer]
    copyright = "© 2025 Lerian Studio. All rights reserved."
    poweredBy = false

# Syntax Highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
    tabWidth = 2

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
    
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Menu Configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

# Privacy Configuration
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Outputs for search
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"