# This file is only needed if you want to use Netlify Identity for authentication
# For AWS Amplify with GitHub OAuth, you'll need a different approach

[build]
  publish = "public"
  command = "hugo --minify"

[context.production.environment]
  HUGO_VERSION = "0.121.1"
  HUGO_ENV = "production"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"