backend:
  name: github
  repo: LerianStudio/blog
  branch: main
  base_url: https://decap-oauth-provider.vercel.app
  auth_endpoint: auth

# This line should *not* be indented
publish_mode: editorial_workflow

# Media files will be stored in the repo
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Site URL for preview
site_url: https://blog.lerian.studio
display_url: https://blog.lerian.studio

# Logo for admin UI
logo_url: /images/lerian-logo.svg

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - {
          label: "Featured Image",
          name: "featured_image",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Image Alt",
          name: "featured_image_alt",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Image Caption",
          name: "featured_image_caption",
          widget: "string",
          required: false,
        }
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options:
          [
            "Architecture",
            "Financial Technology",
            "Development",
            "Product",
            "API Design",
            "Data Security",
          ]
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          [
            "fintech",
            "architecture",
            "cqrs",
            "eda",
            "ledger",
            "midaz",
            "sdk",
            "api-design",
            "software-architecture",
            "crm",
            "customer-management",
            "data-security",
          ]
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", required: false }
          - { label: "Draft", name: "draft", widget: "boolean", default: false }
          - { label: "Content", name: "body", widget: "markdown" }
