backend:
  name: github
  repo: LerianStudio/blog
  branch: main
  base_url: https://decap-oauth-vercel-omqwct67c-fred-amarals-projects.vercel.app
  auth_endpoint: api/auth

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test"
    label: "Test Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
